# Auto-generated by generate_paths.py
# This file is generated from an OpenAPI specification.
# Any changes made directly to this file will be lost.

from strenum import StrEnum


class Device(StrEnum):
    ID = '/device/id'

class Robot(StrEnum):
    FRAMES = '/robot/frames'
    FRAME_POSE = '/robot/frames/{frame_id}/pose'
    WAYPOINTS = '/robot/waypoints'
    JOINTS = '/robot/joints'

class Programs(StrEnum):
    PROGRAMS = '/programs'
    PROGRAM = '/programs/{program_id}'
    PROGRAM_FILE = '/programs/{program_id}/file'
    PROGRAM_EXECUTIONS = '/programs/{program_id}/executions'
    PROGRAM_EXECUTION = '/programs/{program_id}/executions/{execution_id}'
    PROGRAM_STATUS = '/programs/{program_id}/status'

class Auth(StrEnum):
    LOGIN = '/auth/login'

class Users(StrEnum):
    USERS = '/users'
    USER = '/users/{user_id}'
    USER_TOKENS = '/users/{user_id}/tokens'
    USER_PASSWORD = '/users/{user_id}/password'
