# Auto-generated by generate_paths.py
# This file is generated from an OpenAPI specification.
# Any changes made directly to this file will be lost.

from strenum import StrEnum



class Health(StrEnum):
    HEALTH = '/health'



class Reboot(StrEnum):
    REBOOT = '/reboot'



class Shutdown(StrEnum):
    SHUTDOWN = '/shutdown'



class Ready(StrEnum):
    READY = '/ready'



class Api:
    class Device(StrEnum):
        ID = '/api/device/id'
    
    class Robot(StrEnum):
        FRAMES = '/api/robot/frames'
        FRAME_POSE = '/api/robot/frames/{frame_id}/pose'
        WAYPOINTS = '/api/robot/waypoints'
        TRAJECTORY_GENERATIONS = '/api/robot/trajectory/generations'
        TRAJECTORY_EXECUTIONS = '/api/robot/trajectory/executions'
        URDF = '/api/robot/urdf'
        CONFIG = '/api/robot/config'
        CONTROL_MODE = '/api/robot/control-mode'
        JOINTS = '/api/robot/joints'
    
    class Programs(StrEnum):
        PROGRAMS = '/api/programs'
        PROGRAM = '/api/programs/{program_id}'
        PROGRAM_FILE = '/api/programs/{program_id}/file'
        PROGRAM_EXECUTIONS = '/api/programs/{program_id}/executions'
        PROGRAM_EXECUTION = '/api/programs/{program_id}/executions/{execution_id}'
        PROGRAM_STATUS = '/api/programs/{program_id}/status'
    
    class Auth(StrEnum):
        LOGIN = '/api/auth/login'
    
    class Users(StrEnum):
        USERS = '/api/users'
        USER = '/api/users/{user_id}'
        USER_TOKENS = '/api/users/{user_id}/tokens'
        USER_PASSWORD = '/api/users/{user_id}/password'
    
    class Network(StrEnum):
        INTERFACES = '/api/network/interfaces'
        INTERFACE = '/api/network/interfaces/{interface_id}'
        INTERFACE_CONFIG = '/api/network/interfaces/{interface_id}/config'
    
