# Auto-generated by generate_paths.py
# This file is generated from an OpenAPI specification.
# Any changes made directly to this file will be lost.

from strenum import StrEnum


class Authentication(StrEnum):

  LOGIN = '/api/auth/login'
  GET_ALL_USERS = '/api/users'
  CREATE_USER = '/api/users'
  GET_USER = '/api/users/{user_id}'
  DELETE_USER = '/api/users/{user_id}'
  UPDATE_USER = '/api/users/{user_id}'
  UPDATE_USER_PASSWORD = '/api/users/{user_id}/password'
  GET_USER_TOKENS = '/api/users/{user_id}/tokens'
  CREATE_USER_TOKEN = '/api/users/{user_id}/tokens'


class Device(StrEnum):

  HEALTH_CHECK = '/api/device/health'
  GET_DEVICE_ID = '/api/device/id'
  READINESS_CHECK = '/api/device/ready'
  REBOOT = '/api/device/reboot'
  SHUTDOWN = '/api/device/shutdown'
  GET_FIRMWARE_STATE = '/api/firmware'


class Firmware(StrEnum):

  GET_ERROR_REPORT = '/api/firmware/errors'
  CLEAR_FIRMWARE_ERRORS = '/api/firmware/errors'


class Ios(StrEnum):

  GET_IO_STATES = '/api/io'
  UPDATE_IO_STATES = '/api/io'


class Network(StrEnum):

  GET_NETWORK_INTERFACES = '/api/network/interfaces'
  GET_NETWORK_INTERFACE_STATUS = '/api/network/interfaces/{interface_id}'
  GET_NETWORK_INTERFACE_CONFIG = '/api/network/interfaces/{interface_id}/config'
  UPDATE_NETWORK_INTERFACE_CONFIG = '/api/network/interfaces/{interface_id}/config'


class Programs(StrEnum):

  GET_ALL_PROGRAMS = '/api/programs'
  CREATE_PROGRAM = '/api/programs'
  GET_PROGRAMS_EXECUTOR_STATUS = '/api/programs-executor/status'
  UPDATE_PROGRAMS_EXECUTOR_STATUS = '/api/programs-executor/status'
  GET_PROGRAM = '/api/programs/{program_id}'
  DELETE_PROGRAM = '/api/programs/{program_id}'
  UPDATE_PROGRAM = '/api/programs/{program_id}'
  GET_PROGRAM_EXECUTIONS = '/api/programs/{program_id}/executions'
  EXECUTE_PROGRAM = '/api/programs/{program_id}/executions'
  GET_PROGRAM_EXECUTION = '/api/programs/{program_id}/executions/{execution_id}'
  GET_PROGRAM_FILE = '/api/programs/{program_id}/file'
  UPLOAD_PROGRAM_FILE = '/api/programs/{program_id}/file'


class Robot(StrEnum):

  GET_ROBOT_CONFIG = '/api/robot/config'
  GET_ROBOT_CONTROL_MODE = '/api/robot/control-mode'
  SET_ROBOT_CONTROL_MODE = '/api/robot/control-mode'
  GET_ALL_FRAMES = '/api/robot/frames'
  GET_FRAME_POSE = '/api/robot/frames/{frame_id}/pose'
  MOVE_FRAME_TO_POSE = '/api/robot/frames/{frame_id}/pose'
  GET_ROBOT_JOINTS = '/api/robot/joints'
  MOVE_TO_JOINTS = '/api/robot/joints'
  EXECUTE_TRAJECTORY = '/api/robot/trajectory/executions'
  GENERATE_TRAJECTORY = '/api/robot/trajectory/generations'
  GET_ROBOT_URDF = '/api/robot/urdf'
  MOVE_ALONG_WAYPOINTS = '/api/robot/waypoints'
  GET_TRAJECTORY_EXECUTOR_STATUS = '/api/trajectory-executor/status'
  UPDATE_TRAJECTORY_EXECUTOR_STATUS = '/api/trajectory-executor/status'

