# Auto-generated by generate_topics.py
# This file is generated from an AsyncAPI specification.
# Any changes made directly to this file will be lost.

from strenum import StrEnum


class Cmd(StrEnum):
    ROBOT_JOINTS = 'cmd/robot/joints'
    ROBOT_JOG_JOINT = 'cmd/robot/jog/joint'
    ROBOT_JOG_CARTESIAN = 'cmd/robot/jog/cartesian'
    ROBOT_JOG_STOP = 'cmd/robot/jog/stop'
    ROBOT_CONTROL_MODE = 'cmd/robot/control-mode'
    ROBOT_TRAJ_GEN = 'cmd/robot/traj-gen'
    ROBOT_TRAJ_EXEC = 'cmd/robot/traj-exec'

class Ack(StrEnum):
    ROBOT_TRAJ_EXEC = 'ack/robot/traj-exec'

class Robot(StrEnum):
    FRAME_POSE = 'robot/frames/{frame_id}/pose'
    JOINTS = 'robot/joints'
    ROBOT_MOVE_FEEDBACK = 'robot/{cmd_id}/move-feedback'
    CONTROL_MODE = 'robot/control-mode'

class Users(StrEnum):
    USER_LOGGED_IN = 'users/{user_id}/logged-in'
    USER_LOGGED_OUT = 'users/{user_id}/logged-out'

class Programs(StrEnum):
    PROGRAM_EXECUTION_OUTPUT = 'programs/{program_id}/executions/{execution_id}/output'
    PROGRAM_EXECUTION_STATUS = 'programs/{program_id}/executions/{execution_id}/status'

class System(StrEnum):
    METRICS = 'system/metrics'

class Api(StrEnum):
    METRICS = 'api/metrics'
