# Auto-generated by generate_topics.py
# This file is generated from an AsyncAPI specification.
# Any changes made directly to this file will be lost.

from strenum import StrEnum


class Robot(StrEnum):
    JOINTS_CMD = 'robot/joints/cmd'
    FRAME_POSE = 'robot/frames/{frame_id}/pose'
    JOINTS = 'robot/joints'
    ROBOT_MOVE_FEEDBACK = 'robot/{cmd_id}/move-feedback'

class Users(StrEnum):
    USER_LOGGED_IN = 'users/{user_id}/logged-in'
    USER_LOGGED_OUT = 'users/{user_id}/logged-out'

class Programs(StrEnum):
    PROGRAM_EXECUTION_OUTPUT = 'programs/{program_id}/executions/{execution_id}/output'
    PROGRAM_EXECUTION_STATUS = 'programs/{program_id}/executions/{execution_id}/status'

class System(StrEnum):
    METRICS = 'system/metrics'

class Api(StrEnum):
    METRICS = 'api/metrics'
