default:
  image: python:$PYTHON_VERSION-slim
  tags:
    - amd
  cache:
    paths:
      - .cache/pip

variables:
  PYTHON_VERSION: 3.12

.parallel: &parallel
    matrix:
      - PYTHON_VERSION: "3.10"
      - PYTHON_VERSION: "3.11"
      - PYTHON_VERSION: "3.12"
      - PYTHON_VERSION: "3.13"

.dependencies_job:
  stage: build
  before_script:
    - python3 -m venv venv
    - source venv/bin/activate
    - DEPENDENCIES="."
    - if [ -n "$EXTRAS" ]; then DEPENDENCIES="$DEPENDENCIES[$EXTRAS]"; fi
    - if [ -n "$DEPS" ]; then DEPENDENCIES="$DEPENDENCIES $DEPS"; fi
    - pip install --upgrade $DEPENDENCIES
  variables:
    EXTRAS: ""
    DEPS: ""

.doc_job:
  stage: build
  extends: .dependencies_job
  variables:
    EXTRAS: "docs"

.test_job:
  stage: test
  extends: .dependencies_job
  variables:
    EXTRAS: "tests"

.build_job:
  stage: build
  extends: .dependencies_job
  variables:
    DEPS: "build twine"

mypy:
  extends: .test_job
  script:
    - mypy pyniryo/

unit-tests:
  extends: .test_job
  script:
    - export TOXENV=py${PYTHON_VERSION//./}
    - tox
  parallel: *parallel

pages:
  extends: .doc_job
  script:
    - apt update && apt install -y git
    - git fetch --tags --force
    - git checkout $CI_COMMIT_REF_NAME
    - scripts/build_docs_versioned.py public $CI_COMMIT_TAG $(git tag)
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_TAG
  variables:
    GIT_STRATEGY: "clone"

build_package:
  extends: .build_job
  script:
    - python3 -m build
  rules:
    - if: $CI_COMMIT_TAG
  artifacts:
    paths:
      - dist

.upload_package:
  extends: .build_job
  needs:
    - build_package
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - twine upload --repository-url $REGISTRY_URL dist/*

upload_staging:
  extends: .upload_package
  variables:
    TWINE_USERNAME: gitlab-ci-token
    TWINE_PASSWORD: $CI_JOB_TOKEN
    REGISTRY_URL: $CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/pypi

upload_prod:
  extends: .upload_package
  variables:
    TWINE_USERNAME: __token__
    TWINE_PASSWORD: $PYPI_TOKEN
    REGISTRY_URL: https://upload.pypi.org/legacy/
  when: manual

docker-build:
  image: $DIND_BUILDER_IMAGE
  stage: deploy
  inherit:
    default: false
  tags:
    - aws
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - >
      export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s"
      $(aws sts assume-role --role-arn arn:aws:iam::$ACCOUNT_ID:role/infra@app_runner_jobs --role-session-name "ImageBuild"
      --duration-seconds 3600
      --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]'
      --output text))
    - env
    - aws ecr get-login-password | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.eu-west-3.amazonaws.com
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
  script:
    - docker run --privileged --rm tonistiigi/binfmt --install all
    - docker buildx create --use --name builder --driver docker-container
    - docker buildx inspect --bootstrap
    - docker buildx build
        --provenance=false
        --platform linux/amd64,linux/arm64
        --cache-from $CI_REGISTRY_IMAGE:cache
        --cache-to type=registry,ref=$CI_REGISTRY_IMAGE:cache,mode=max
        --build-arg PYTHON_VERSION=${PYTHON_VERSION}
        -f .docker/Dockerfile
        $DOCKER_TAGS
        --push .
  parallel: *parallel
  variables:
    ACCOUNT_ID: "374724054640"
    AWS_REGION: eu-west-3
    DIND_BUILDER_IMAGE: 016571999676.dkr.ecr.eu-west-3.amazonaws.com/app/ci/docker/docker
    DOCKER_HOST: "unix:///var/run/docker.sock"
    DOCKER_BUILDKIT: 1
    DOCKER_TLS_CERTDIR: ""
  rules:
    - if: '$CI_COMMIT_BRANCH == "master-nate" && $CI_COMMIT_TAG == null'
      variables:
        DOCKER_TAGS: |
          -t $CI_REGISTRY_IMAGE:$PYTHON_VERSION-slim
    - if: '$CI_COMMIT_TAG != null'
      variables:
        DOCKER_TAGS: |
          -t ${ACCOUNT_ID}.dkr.ecr.eu-west-3.amazonaws.com/$CI_PROJECT_PATH:$PYTHON_VERSION-slim
          -t $CI_REGISTRY_IMAGE:$PYTHON_VERSION-slim
          -t ${ACCOUNT_ID}.dkr.ecr.eu-west-3.amazonaws.com/$CI_PROJECT_PATH:$PYTHON_VERSION-slim-$CI_COMMIT_TAG
          -t $CI_REGISTRY_IMAGE:$PYTHON_VERSION-slim-$CI_COMMIT_TAG

promote_prod:
  stage: deploy
  image: $DIND_BUILDER_IMAGE
  dependencies: []
  variables:
      GIT_STRATEGY: none
      ACCOUNT_ID: "458204441573"
      AWS_REGION: eu-west-3
      DIND_BUILDER_IMAGE: 016571999676.dkr.ecr.eu-west-3.amazonaws.com/app/ci/docker/docker
      DOCKER_HOST: "unix:///var/run/docker.sock"
      DOCKER_BUILDKIT: 1
      DOCKER_TLS_CERTDIR: ""
  parallel:
    matrix:
      - PYTHON_VERSION: [ "3.10", "3.11", "3.12" ]
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - >
      export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s"
      $(aws sts assume-role --role-arn arn:aws:iam::$ACCOUNT_ID:role/infra@app_runner_jobs --role-session-name "ImageBuild"
      --duration-seconds 3600
      --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]'
      --output text))
    - env
    - aws ecr get-login-password | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.eu-west-3.amazonaws.com
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
  script:
    - docker buildx imagetools create -t ${ACCOUNT_ID}.dkr.ecr.eu-west-3.amazonaws.com/$CI_PROJECT_PATH:$PYTHON_VERSION-slim-$CI_COMMIT_TAG  $CI_REGISTRY_IMAGE:$PYTHON_VERSION-slim-$CI_COMMIT_TAG
  rules:
    - if: $CI_COMMIT_TAG
      when: manual


mirror_github:
  image: $CI_REGISTRY/robot/ned/development-tools/development-tools:latest
  stage: deploy
  dependencies: []
  variables:
    GIT_STRATEGY: none
    GITHUB_REPOSITORY: git@github.com:NiryoRobotics/pyniryo.git
  before_script: []
  script:
    - eval $(ssh-agent)
    - chmod 600 $GITHUB_SSH_KEY
    - ssh-add $GITHUB_SSH_KEY
    - mkdir -p ~/.ssh
    - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
    - git clone --bare $CI_REPOSITORY_URL
    - cd $CI_PROJECT_NAME.git
    - git push $GITHUB_REPOSITORY $CI_COMMIT_SHA:refs/heads/master --tags -f
  rules:
    - if: $CI_COMMIT_TAG
      when: manual
