# generated by generate_pydantic_models.py
#   timestamp: 2025-11-24T11:25:44.601979

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional
from uuid import UUID

from pydantic import BaseModel, Field, RootModel


class Planner(Enum):
    """The motion planner to use for generating the joint movement trajectory. If not specified, the default planner will be used.
"""
    RRTCONNECT = 'RRTConnect'
    RRT_ = 'RRT*'
    PRM_ = 'PRM*'
    LIN = 'LIN'
    PTP = 'PTP'
    CIRC = 'CIRC'


class Value(Enum):
    """The value of the digital input/output."""
    HIGH = 'HIGH'
    LOW = 'LOW'


class State(Enum):
    """The state of the move command."""
    IDLE = 'idle'
    GENERATING_TRAJECTORY = 'generating_trajectory'
    ERROR_GENERATING_TRAJECTORY = 'error_generating_trajectory'
    LOADING_TRAJECTORY = 'loading_trajectory'
    ERROR_LOADING_TRAJECTORY = 'error_loading_trajectory'
    EXECUTING_TRAJECTORY = 'executing_trajectory'
    ERROR_EXECUTING_TRAJECTORY = 'error_executing_trajectory'
    DONE = 'done'


class Status(Enum):
    """The status of the program's execution."""
    RUNNING = 'running'
    COMPLETED = 'completed'
    FAILED = 'failed'
    PAUSED = 'paused'




class Dummy(BaseModel):
    pass


class Pose(BaseModel):
    position: Optional[Dict[str, Any]] = None
    orientation: Optional[Dict[str, Any]] = None


class MoveJoints(BaseModel):
    command_id: UUID = Field(..., description='Unique identifier for the command.')
    joints: List[float] = Field(..., description='The number of joints should be equal to the number of joints of the robot')
    planner: Optional[Planner] = Field(None, description='The motion planner to use for generating the joint movement trajectory. If not specified, the default planner will be used.\n')


class Joints(RootModel[List[float]]):
    """The number of joints should be equal to the number of joints of the robot"""
    root: List[float] = Field(..., description='The number of joints should be equal to the number of joints of the robot')


class DigitalIO(BaseModel):
    id: Optional[UUID] = Field(None, description='The unique identifier of the digital input/output.')
    value: Optional[Value] = Field(None, description='The value of the digital input/output.')


class AnalogIO(BaseModel):
    id: Optional[UUID] = Field(None, description='The identifier of the analog input/output.')
    value: Optional[float] = Field(None, description='The value of the analog input/output, in volts.')


class UserEvent(BaseModel):
    pass


class MoveFeedback(BaseModel):
    state: Optional[State] = Field(None, description='The state of the move command.')
    message: Optional[str] = Field(None, description='A human-readable message describing the state of the move command.')


class ProgramExecutionOutput(BaseModel):
    output: str = Field(..., description='The output data from the program execution.')
    eof: bool = Field(..., description='Indicates if the end of the output stream has been reached.')


class ProgramExecutionStatus(BaseModel):
    status: Status = Field(..., description='The status of the program\'s execution.')
