[mypy]
python_version = 3.12
plugins = pydantic.mypy

check_untyped_defs = True
disallow_untyped_defs = True
;ignore_missing_imports = True
warn_unused_ignores = True
strict_optional = True
;exclude =
strict = True

[mypy-pyniryo.ned.*]
ignore_errors = True
follow_imports = silent