# Auto-generated by generate_paths.py
# This file is generated from an OpenAPI specification.
# Any changes made directly to this file will be lost.

from enum import StrEnum


class RobotPaths(StrEnum):
    TCP_POSE = '/robot/tcp-pose'
    JOINTS = '/robot/joints'
    TASKS_PICK_AND_PLACE = '/robot/tasks/pick-and-place'
    MOTOR_STATUS = '/robot/motors/{motor_id}/status'
    CALIBRATION = '/robot/calibration'
    STATUS = '/robot/status'
    DESCRIPTION_MODEL = '/robot/description/model'
    DESCRIPTION_CAPABILITIES = '/robot/description/capabilities'
    PARAMETERS = '/robot/parameters'

class LogsPaths(StrEnum):
    LOGS = '/logs'
    LOG = '/logs/{service_id}'
    LEVEL = '/logs/level'
    LOG_LEVEL = '/logs/{service_id}/level'

class ToolsPaths(StrEnum):
    TOOLS = '/tools'
    TOOL = '/tools/{tool_id}'
    TOOL_TASKS_STATE = '/tools/{tool_id}/tasks/state'

class IoPaths(StrEnum):
    DIGITAL_INPUTS = '/io/digital-inputs'
    DIGITAL_INPUT = '/io/digital-inputs/{di_id}'
    DIGITAL_OUTPUTS = '/io/digital-outputs'
    DIGITAL_OUTPUT = '/io/digital-outputs/{do_id}'
    ANALOG_INPUTS = '/io/analog-inputs'
    ANALOG_INPUT = '/io/analog-inputs/{ai_id}'
    ANALOG_OUTPUTS = '/io/analog-outputs'
    ANALOG_OUTPUT = '/io/analog-outputs/{ao_id}'

class ProgramsPaths(StrEnum):
    PROGRAMS = '/programs'
    PROGRAM = '/programs/{program_id}'
    PROGRAM_EXECUTIONS = '/programs/{program_id}/executions'
    PROGRAM_EXECUTION = '/programs/{program_id}/executions/{execution_id}'
    PROGRAM_STATUS = '/programs/{program_id}/status'
    TASKS_DIAGNOSTIC = '/programs/tasks/diagnostic'

class SystemPaths(StrEnum):
    VERSIONS = '/system/versions'

class LoginPaths(StrEnum):
    LOGIN = '/login'

class UsersPaths(StrEnum):
    USERS = '/users'
    USER = '/users/{user_id}'
    USER_TOKENS = '/users/{user_id}/tokens'
    USER_PASSWORD = '/users/{user_id}/password'
