#!/usr/bin/env python3

import argparse
import re
from pathlib import Path

import yaml
from jinja2 import Template

template_code = """\
# Auto-generated by {{ script_name }}
# This file is generated from an AsyncAPI specification.
# Any changes made directly to this file will be lost.

from strenum import StrEnum

{% for group_name, group in groups.items() %}
class {{ group_name }}(StrEnum):
    {%- for name, value in group.items() %}
    {{ name }} = '{{ value }}'
    {%- endfor %}
{% endfor %}
"""


def normalize_class_name(name: str) -> str:
    """
    Normalize a string to be a valid Python class name.
    """
    name = re.sub(r'\W|^(?=\d)', '_', name)
    return ''.join(part.capitalize() for part in name.split('_'))


def normalize_enum_name(name: str) -> str:
    """
    Normalize a string to be a valid Python enum name.
    """
    name = re.sub(r'\W|^(?=\d)', '_', name)
    return name.upper()


def enum_name(path_parts: list):
    """
    Generate a name for the enum based on the group name and channel path.
    """
    group_name = path_parts[0].capitalize()
    if len(path_parts) == 1:
        return normalize_class_name(group_name), normalize_enum_name(group_name)

    name_parts = []
    # Start at 1 because 0 is the group name
    for ix, part in enumerate(path_parts[1:], start=1):
        # If the format is /things/{thing_id}, name the enum THING
        if part.startswith('{'):
            if len(name_parts) == 0:
                name_parts.append(group_name)
            name_parts[-1] = name_parts[-1].rstrip('s')
        else:
            name_parts.append(part.capitalize())

    name = '_'.join(name_parts).upper()
    name = re.sub(r'\W|^(?=\d)', '_', name)
    return normalize_class_name(group_name), normalize_enum_name(name)


def strip_device_prefix(address: str) -> str:
    """
    Strip the device/{device_id}/ prefix from a channel address.
    
    Args:
        address: Channel address (e.g., 'device/{device_id}/robot/joints')
        
    Returns:
        Address without device prefix (e.g., 'robot/joints')
    """
    # Remove 'device/{device_id}/' prefix if present
    if address.startswith('device/{device_id}/'):
        return address[len('device/{device_id}/'):]
    return address


def get_args():
    """
    Get the arguments from the command line.
    """
    default_output = Path('./topics_gen.py')
    parser = argparse.ArgumentParser(
        description='Generate Python Enums from AsyncAPI channels.',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )
    parser.add_argument('input', type=Path, help='Input AsyncAPI file path.')
    parser.add_argument(
        '-o',
        '--output',
        required=True,
        type=Path,
        help='Output file path for generated Enums.',
        default=default_output
    )
    parser.add_argument(
        '--keep-device-prefix',
        action='store_true',
        help='Keep the device/{device_id}/ prefix in channel values (default: strip it)'
    )
    return parser.parse_args()


def main():
    args = get_args()

    # Load AsyncAPI specification
    with open(args.input, 'r') as f:
        specification = yaml.safe_load(f)

    # Extract channels
    if 'channels' not in specification:
        print("Error: No 'channels' section found in AsyncAPI file")
        return

    channels = specification['channels']
    
    # Extract channel addresses
    channel_addresses = {}
    for channel_name, channel_data in channels.items():
        if isinstance(channel_data, dict) and 'address' in channel_data:
            address = channel_data['address']
            # Store both original and stripped versions
            channel_addresses[channel_name] = {
                'original': address,
                'stripped': strip_device_prefix(address)
            }

    # Group channels by first segment (using stripped version for grouping)
    grouped_channels = {}
    for channel_name, addresses in channel_addresses.items():
        # Use stripped address for determining group and enum name
        stripped_address = addresses['stripped']
        
        # Split the address into parts (no leading slash in AsyncAPI addresses)
        path_parts = stripped_address.split('/')
        
        # Determine group name and enum name based on stripped address
        group_name, enum_member_name = enum_name(path_parts)
        
        # Use original or stripped address for the value based on flag
        value = addresses['original'] if args.keep_device_prefix else addresses['stripped']
        
        if group_name not in grouped_channels:
            grouped_channels[group_name] = {}
        grouped_channels[group_name][enum_member_name] = value

    # Generate output using template
    template = Template(template_code)
    rendered_code = template.render(script_name=Path(__file__).name, groups=grouped_channels)
    
    # Write to output file
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered_code)
    
    print(f"Generated topics enums written to {args.output}")


if __name__ == '__main__':
    main()
