#!/usr/bin/env python3

import argparse
import re
import sys
from pathlib import Path
from keyword import iskeyword
from collections import defaultdict
from typing import Dict, List

# openapi3-parser
from openapi_parser import parse
from jinja2 import Template

# Template now supports multiple classes based on tags
template_code = """\
# Auto-generated by {{ script_name }}
# This file is generated from an OpenAPI specification.
# Any changes made directly to this file will be lost.

from strenum import StrEnum

{% for class_name, paths in grouped_paths.items() %}
class {{ class_name }}(StrEnum):
{% for op_id, path in paths.items() %}
  {{ op_id }} = '{{ path }}'{% endfor %}

{% endfor %}
"""


def get_args():
    """
    Get the arguments from the command line.
    """
    default_output = Path('./paths_gen.py')
    parser = argparse.ArgumentParser(description='Generate grouped Python Enums from OpenAPI paths.',
                                     formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument('input', type=Path, help='Input OpenAPI file path.')
    parser.add_argument('-o',
                        '--output',
                        type=Path,
                        default=default_output,
                        help='Output file path for generated Enums.')
    return parser.parse_args()


def to_screaming_snake_case(text: str) -> str:
    """
    Converts camelCase/PascalCase to SCREAMING_SNAKE_CASE.
    Example: getHTTPResponse -> GET_HTTP_RESPONSE
    """
    if not text:
        return "UNKNOWN_OPERATION"

    # Insert underscore between lower/digit and Upper
    s1 = re.sub(r'([a-z0-9])([A-Z])', r'\1_\2', text)
    # Insert underscore between Upper and Upper followed by lower
    s2 = re.sub(r'([A-Z])([A-Z][a-z])', r'\1_\2', s1)

    result = s2.upper()
    result = re.sub(r'[^A-Z0-9_]', '_', result)
    return result


def to_pascal_case(text: str) -> str:
    """
    Converts 'User Management' or 'user_management' to 'UserManagement'.
    Used for generating Class names.
    """
    # Replace non-alphanumeric chars with space
    text = re.sub(r'[^a-zA-Z0-9]', ' ', text)
    # Capitalize first letter of every word and join
    return ''.join(word.capitalize() for word in text.split())


def sanitize_variable_name(name: str) -> str:
    """Ensure the name is a valid Python identifier."""
    if not name:
        return "UNKNOWN"
    if name[0].isdigit():
        name = f"_{name}"
    if iskeyword(name.lower()):
        name = f"{name}_"
    return name


def main():
    args = get_args()

    if not args.input.exists():
        print(f"Error: Input file '{args.input}' not found.")
        sys.exit(1)

    try:
        specification = parse(str(args.input))
    except Exception as e:
        print(f"Error parsing OpenAPI spec: {e}")
        sys.exit(1)

    if not specification.paths:
        print("Warning: No paths found in specification.")
        return

    # Data structure: {'ClassName': {'OP_ID': '/url/path'}}
    grouped_paths: Dict[str, Dict[str, str]] = defaultdict(dict)

    total_paths = 0

    for path in specification.paths:
        for operation in path.operations:
            if not operation.operation_id:
                print(f"Skipping {operation.method.name} {path.url} (No operationId)")
                continue

            # 1. Determine the Class Name from Tags
            if operation.tags:
                # Use the first tag to group
                raw_tag = operation.tags[0].name if hasattr(operation.tags[0], 'name') else str(operation.tags[0])
                class_name = to_pascal_case(raw_tag)
            else:
                class_name = "Default"

            # 2. Determine the Variable Name
            var_name = sanitize_variable_name(to_screaming_snake_case(operation.operation_id))

            # Check for duplicates within the same class
            if var_name in grouped_paths[class_name]:
                print(f"Warning: Duplicate key '{var_name}' in class '{class_name}'. Skipping.")
                continue

            grouped_paths[class_name][var_name] = path.url
            total_paths += 1

    # Sort classes alphabetically, and their contents alphabetically
    sorted_groups = {}
    for k in sorted(grouped_paths.keys()):
        sorted_groups[k] = dict(sorted(grouped_paths[k].items(), key=lambda item: item[1]))

    template = Template(template_code)
    rendered_code = template.render(script_name=Path(__file__).name, grouped_paths=sorted_groups)

    try:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(rendered_code)
        print(f"Successfully generated {total_paths} paths across {len(sorted_groups)} classes in {args.output}")
    except OSError as e:
        print(f"Error writing output file: {e}")
        sys.exit(1)


if __name__ == '__main__':
    main()
