# generated by scripts/generate_asyncapi_models.py
#   timestamp: 2026-03-05T18:04:51.495477

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional
from uuid import UUID

from pydantic import BaseModel, Field


class Planner(Enum):
    """The motion planner to use for generating the joint movement trajectory. If not specified, the default planner will be used.
"""
    RRTCONNECT = 'RRTConnect'
    RRT_ = 'RRT*'
    PRM_ = 'PRM*'
    LIN = 'LIN'
    PTP = 'PTP'
    CIRC = 'CIRC'


class State(Enum):
    """The state of the move command."""
    IDLE = 'idle'
    PREPARING = 'preparing'
    ERROR_PREPARING = 'error_preparing'
    GENERATING_TRAJECTORY = 'generating_trajectory'
    ERROR_GENERATING_TRAJECTORY = 'error_generating_trajectory'
    LOADING_TRAJECTORY = 'loading_trajectory'
    ERROR_LOADING_TRAJECTORY = 'error_loading_trajectory'
    EXECUTING_TRAJECTORY = 'executing_trajectory'
    ERROR_EXECUTING_TRAJECTORY = 'error_executing_trajectory'
    DONE = 'done'
    PAUSED = 'paused'


class Status(Enum):
    """The status of the execution."""
    PENDING = 'pending'
    RUNNING = 'running'
    COMPLETED = 'completed'
    FAILED = 'failed'
    PAUSED = 'paused'
    STOPPED = 'stopped'


class MType(Enum):
    """The type of the metric"""
    INT = 'int'
    FLOAT = 'float'
    STRING = 'string'
    BOOL = 'bool'
    DATETIME = 'datetime'
    DURATION = 'duration'


class MotionType(Enum):
    """Type of motion planning to use"""
    P2P_ARTICULAR = 'p2p_articular'
    P2P_LINEAR = 'p2p_linear'
    WAYPOINTS = 'waypoints'


class Mode(Enum):
    """Control mode identifier:
- 1: TRAJECTORY (default) - Command controlled by trajectory executor, position regulation active
- 2: JOG - Command generated by jog interface, position regulation active
- 3: SPEED - Manual speed command, position regulation inactive
"""
    _1 = '1'
    _2 = '2'
    _3 = '3'


class ModeName(Enum):
    """Human-readable control mode name"""
    TRAJECTORY = 'trajectory'
    JOG = 'jog'
    SPEED = 'speed'




class Dummy(BaseModel):
    pass


class Pose(BaseModel):
    position: Dict[str, Any] = Field(...)
    orientation: Dict[str, Any] = Field(...)


class MoveJoints(BaseModel):
    command_id: UUID = Field(..., description='Unique identifier for the command.')
    joints: List[float] = Field(..., description='The number of joints should be equal to the number of joints of the robot')
    planner: Optional[Planner] = Field(None, description='The motion planner to use for generating the joint movement trajectory. If not specified, the default planner will be used.\n')
    add_start: Optional[bool] = Field(None, description='if true, current joint state is added as trajectory start')


class JogJoint(BaseModel):
    """Joint space jog command with joint velocities"""
    velocities: List[float] = Field(..., description='Array of joint velocities in rad/s. Length must match number of robot joints.')


class JogCartesian(BaseModel):
    """Cartesian space jog command with linear and angular velocities"""
    linear: List[float] = Field(..., description='Linear velocities [vx, vy, vz] in m/s')
    angular: List[float] = Field(..., description='Angular velocities [wx, wy, wz] in rad/s')
    frame_id: Optional[str] = Field('tcp', description='Reference frame for the velocities (e.g., "tcp", "base_link", "world")')


class JogStop(BaseModel):
    """Stop jog command - stops all jogging motion"""
    pass


class Joints(BaseModel):
    timestamp: int = Field(..., description='Unix timestamp in milliseconds when the joint state was captured')
    positions: List[float] = Field(..., description='The number of joints should be equal to the number of joints of the robot')
    velocities: List[float] = Field(..., description='Joint velocities in radians per second')


class FirmwareState(BaseModel):
    status: Optional[str] = Field(None, description='The value of the firmware state.')
    container_status: Optional[str] = Field(None, description='The status of the ros-robot container (running, stopped, not_found, unknown).')


class IOStates(BaseModel):
    digital_inputs: Optional[List[Dict[str, Any]]] = None
    digital_outputs: Optional[List[Dict[str, Any]]] = None
    analog_inputs: Optional[List[Dict[str, Any]]] = None
    analog_outputs: Optional[List[Dict[str, Any]]] = None


class DigitalIOState(BaseModel):
    value: bool = Field(..., description='The value of the digital input/output.')


class AnalogIOState(BaseModel):
    value: float = Field(..., description='The value of the analog input/output, in volts.')


class UserEvent(BaseModel):
    pass


class MoveFeedback(BaseModel):
    state: State = Field(..., description='The state of the move command.')
    message: str = Field(..., description='A human-readable message describing the state of the move command.')


class ProgramExecutionOutput(BaseModel):
    output: str = Field(..., description='The output data from the program execution.')
    eof: bool = Field(..., description='Indicates if the end of the output stream has been reached.')


class ProgramsExecutorStatus(BaseModel):
    execution: Optional[Dict[str, Any]] = None
    status: Status = Field(..., description='The status of the execution.')
    sigkill: Optional[bool] = Field(False, description='Whether to use SIGKILL to stop the program execution. If false, SIGTERM will be used.')


class SystemMetrics(BaseModel):
    """System metrics including host resources and Docker container/volume metrics"""
    timestamp: Optional[datetime] = Field(None, description='RFC3339 formatted timestamp')
    host: Optional[Dict[str, Any]] = Field(None, description='Host system metrics')
    containers: Optional[List[Dict[str, Any]]] = Field(None, description='Docker container metrics')
    volumes: Optional[List[Dict[str, Any]]] = Field(None, description='Docker volume metrics')


class ApiMetrics(BaseModel):
    pass


class CustomMetric(BaseModel):
    name: str = Field(..., description='The name of the metric.')
    value: str = Field(..., description='The value of the metric.')
    m_type: Optional[MType] = Field(None, description='The type of the metric')


class TrajectoryExecution(BaseModel):
    command_id: UUID = Field(..., description='Unique identifier for the command.')
    trajectory: List[Dict[str, Any]] = Field(..., description='Generated trajectory as array of timestamped joint positions')


class TrajectoryGeneration(BaseModel):
    waypoints: List[Dict[str, Any]] = Field(..., description='List of waypoints to generate trajectory for')
    motion_type: MotionType = Field(..., description='Type of motion planning to use')
    add_start: Optional[bool] = Field(None, description='if true, current joint state is added as trajectory start')


class ControlMode(BaseModel):
    mode: Mode = Field(..., description='Control mode identifier:\n- 1: TRAJECTORY (default) - Command controlled by trajectory executor, position regulation active\n- 2: JOG - Command generated by jog interface, position regulation active\n- 3: SPEED - Manual speed command, position regulation inactive\n')
    mode_name: ModeName = Field(..., description='Human-readable control mode name')


class Ack(BaseModel):
    """Ack message"""
    command_id: str = Field(..., description='command id')
    status: bool = Field(..., description='defines if the command is correctly handled')
    message: Optional[str] = Field(None, description='information about the status if any')


class SpeedFactor(BaseModel):
    speed_factor: float = Field(...)
