# generated by datamodel-codegen:
#   filename:  openapi.yml
#   timestamp: 2026-03-03T09:00:25+00:00

from __future__ import annotations
from pydantic import BaseModel, EmailStr, Field, RootModel, SecretStr
from enum import Enum, IntEnum
from uuid import UUID
from datetime import datetime
from ipaddress import IPv4Address


class DeviceID(BaseModel):
    device_id: str = Field(..., examples=["f15bb7fca5f6408a8d9e0bca05bd5cf0"])


class Joints(RootModel[list[float]]):
    """
    The number of joints should be equal to the number of joints of the robot
    """

    root: list[float] = Field(..., examples=[[0.0, 1.25, 0.0, 0.0, 0.0, 0.0]])
    """
    The number of joints should be equal to the number of joints of the robot
    """


class Point(BaseModel):
    x: float
    y: float
    z: float


class Quaternion(BaseModel):
    x: float
    y: float
    z: float
    w: float


class Planner(Enum):
    """
    The motion planner to use for generating the joint movement trajectory. If not specified, the default planner will be used.

    """

    RRT_CONNECT = "RRTConnect"
    RRT_ = "RRT*"
    PRM_ = "PRM*"
    LIN = "LIN"
    PTP = "PTP"
    CIRC = "CIRC"


class PIDGains(BaseModel):
    p: float | None = None
    """
    Proportional gain
    """
    i: float | None = None
    """
    Integral gain
    """
    d: float | None = None
    """
    Derivative gain
    """
    ff: float | None = None
    """
    Feed-forward gain
    """
    max_i: float | None = None
    """
    Maximum integral term
    """
    max_out: float | None = None
    """
    Maximum output
    """


class Mode(IntEnum):
    """
    Control mode identifier:
    - 1: TRAJECTORY (default) - Command controlled by trajectory executor, position regulation active
    - 2: JOG - Command generated by jog interface, position regulation active
    - 3: SPEED - Manual speed command, position regulation inactive

    """

    INTEGER_1 = 1
    INTEGER_2 = 2
    INTEGER_3 = 3


class ModeName(Enum):
    """
    Human-readable control mode name
    """

    TRAJECTORY = "trajectory"
    JOG = "jog"
    SPEED = "speed"


class ControlMode(BaseModel):
    mode: Mode = Field(..., examples=[1])
    """
    Control mode identifier:
    - 1: TRAJECTORY (default) - Command controlled by trajectory executor, position regulation active
    - 2: JOG - Command generated by jog interface, position regulation active
    - 3: SPEED - Manual speed command, position regulation inactive

    """
    mode_name: ModeName = Field(..., examples=["trajectory"])
    """
    Human-readable control mode name
    """


class FirmwareState(BaseModel):
    status: str | None = None
    """
    The value of the firmware state.
    """


class ErrorReport(BaseModel):
    message: str


class MoveJoints(BaseModel):
    command_id: UUID
    """
    Unique identifier for the command.
    """
    joints: Joints
    planner: Planner | None = None
    """
    The motion planner to use for generating the joint movement trajectory. If not specified, the default planner will be used.

    """
    add_start: bool | None = None
    """
    if true, current joint state is added as trajectory start
    """


class FeedbackResponse(BaseModel):
    feedback_id: UUID
    """
    Unique identifier for the feedback of the corresponding action.
    """


class Type(Enum):
    PYTHON3_9 = "python3.9"
    PYTHON3_10 = "python3.10"
    PYTHON3_11 = "python3.11"
    PYTHON3_12 = "python3.12"
    GOLANG = "golang"


class Program(BaseModel):
    id: UUID | None = None
    name: str | None = None
    """
    The name of the program.
    """
    type: Type | None = None


class Type1(Enum):
    PYTHON = "python"


class UploadProgram(BaseModel):
    file: bytes
    name: str | None = None
    """
    The name of the program. If not provided, the file name will be used.
    """
    type: Type1


class ProgramExecutionContext(BaseModel):
    environment: dict[str, str] | None = None
    arguments: list[str] | None = None


class ExecutorStatus(Enum):
    """
    The status of the execution.
    """

    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    PAUSED = "paused"
    STOPPED = "stopped"


class TrajectoryExecutorStatus(BaseModel):
    command_id: UUID | None = None
    """
    Unique identifier for the move command.
    """
    status: ExecutorStatus


class DigitalIOState(BaseModel):
    value: bool
    """
    The value of the digital input/output.
    """


class AnalogIOState(BaseModel):
    value: float
    """
    The value of the analog input/output, in volts.
    """


class Login(BaseModel):
    login: str
    password: str
    expires_at: datetime | None = None


class Role(BaseModel):
    id: int
    name: str


class NewUser(BaseModel):
    email: EmailStr
    name: str
    role_id: int
    password: str


class TokenCreation(BaseModel):
    expires_at: datetime


class UpdatePassword(BaseModel):
    old_password: str
    new_password: str


class MotionType(Enum):
    """
    Type of motion planning to use
    """

    P2P_ARTICULAR = "p2p_articular"
    P2P_LINEAR = "p2p_linear"
    WAYPOINTS = "waypoints"


class JointsStamped(BaseModel):
    joints: Joints
    timestamp: float
    """
    Timestamp in seconds from trajectory start
    """
    velocities: list[float] | None = None
    """
    Joint velocities at this timestamp (optional)
    """
    accelerations: list[float] | None = None
    """
    Joint accelerations at this timestamp (optional)
    """


class NetworkInterfaceType(Enum):
    ETHERNET = "ethernet"
    WIFI = "wifi"


class NetworkIpConfig(BaseModel):
    ip: IPv4Address
    """
    Static IP address assigned to the device.
    """
    netmask: IPv4Address
    """
    Subnet mask for the network.
    """
    gateway: IPv4Address
    """
    Default gateway IP address.
    """
    dns: list[IPv4Address] | None = None
    """
    List of DNS server IP addresses.
    """
    dhcp: bool
    """
    Indicates whether DHCP is enabled for the network configuration. If true, the IP, netmask, gateway, and DNS fields may be ignored.
    """


class NetworkInterfaceConfigEthernet(BaseModel):
    link_local: bool
    """
    Indicates whether link-local addressing (169.254.x.x) is enabled in fallback for the Ethernet interface.
    """


class NetworkInterfaceConfigWiFi(BaseModel):
    ssid: str
    username: str | None = None
    password: SecretStr | None = None


class NetworkInterfaceConfig(BaseModel):
    enabled: bool
    """
    Indicates whether the network interface is enabled.
    """
    ipv4: NetworkIpConfig
    ethernet: NetworkInterfaceConfigEthernet | None = None
    wifi: NetworkInterfaceConfigWiFi | None = None


class MType(Enum):
    """
    The type of the metric
    """

    INT = "int"
    FLOAT = "float"
    STRING = "string"
    BOOL = "bool"
    DATETIME = "datetime"
    DURATION = "duration"


class CustomMetric(BaseModel):
    name: str
    """
    The name of the metric.
    """
    value: str
    """
    The value of the metric.
    """
    m_type: MType | None = None
    """
    The type of the metric
    """


class SpeedFactor(BaseModel):
    speed_factor: float = Field(..., examples=[0.5])


class Pose(BaseModel):
    position: Point
    orientation: Quaternion


class JointConfig(BaseModel):
    name: str | None = Field(None, examples=["joint_1"])
    """
    Joint name
    """
    type: str | None = Field(None, examples=["revolute"])
    """
    Joint type (revolute, prismatic, continuous)
    """
    position_limit_min: float | None = Field(None, examples=[-3.14159])
    """
    Minimum position limit (radians or meters)
    """
    position_limit_max: float | None = Field(None, examples=[3.14159])
    """
    Maximum position limit (radians or meters)
    """
    velocity_limit: float | None = Field(None, examples=[2.0])
    """
    Maximum velocity limit (rad/s or m/s)
    """
    acceleration_limit: float | None = Field(None, examples=[5.0])
    """
    Maximum acceleration limit (rad/s² or m/s²)
    """
    effort_limit: float | None = Field(None, examples=[10.0])
    """
    Maximum effort/torque limit (Nm or N)
    """
    pid_position: PIDGains | None = None
    pid_velocity: PIDGains | None = None


class MoveFrame(BaseModel):
    command_id: UUID
    """
    Unique identifier for the command.
    """
    pose: Pose
    reference_frame: str | None = None
    """
    The reference frame for the movement. If not specified, defaults to the robot's base frame.
    """
    planner: Planner | None = None
    add_start: bool | None = None
    """
    if true, current joint state is added as trajectory start
    """


class ExecuteProgram(BaseModel):
    execution_id: UUID
    context: ProgramExecutionContext


class ProgramExecution(BaseModel):
    id: UUID
    programId: UUID
    context: ProgramExecutionContext
    startedAt: datetime | None = Field(...)
    finishedAt: datetime | None = Field(...)
    exitCode: int | None = Field(...)
    status: ExecutorStatus | None = None


class DigitalIO(DigitalIOState):
    id: str
    """
    The identifier of the digital input/output.
    """


class AnalogIO(AnalogIOState):
    id: str
    """
    The identifier of the analog input/output.
    """


class User(BaseModel):
    id: UUID
    login: str
    name: str
    role: Role


class TokenInfo(TokenCreation):
    id: UUID
    expires_at: datetime
    created_at: datetime


class Trajectory(RootModel[list[JointsStamped]]):
    """
    Generated trajectory as array of timestamped joint positions
    """

    root: list[JointsStamped]
    """
    Generated trajectory as array of timestamped joint positions
    """


class TrajectoryExecution(BaseModel):
    command_id: UUID
    """
    Unique identifier for the command.
    """
    trajectory: Trajectory


class NetworkInterfaceStatus(BaseModel):
    id: str
    """
    Unique identifier for the network interface.
    """
    type: NetworkInterfaceType
    mac_address: str
    """
    MAC address of the network interface.
    """
    connected: bool
    """
    Indicates whether the network interface is currently connected.
    """
    state: NetworkIpConfig
    ethernet: NetworkInterfaceConfigEthernet | None = None
    wifi: NetworkInterfaceConfigWiFi | None = None


class CustomMetrics(BaseModel):
    metrics: list[CustomMetric]
    metrics_id: str
    """
    The unique identifier for the metric, used for referencing in other parts of the system.
    """


class Waypoint(BaseModel):
    joints: Joints | None = None
    pose: Pose | None = None
    frame_id: str | None = None
    """
    Identifier for the frame associated with the waypoint.
    """
    reference_frame: str | None = None
    """
    The reference frame for the movement. If not specified, defaults to the robot's base frame.
    """
    planner: Planner | None = None
    blending_radius: float = 0
    """
    The blending radius in meters for smooth pass-through motion at this waypoint. A value of 0 means the robot will stop at this waypoint. Non-zero values enable continuous motion through intermediate waypoints.
    """
    velocity_factor: float = 1
    """
    A scaling factor for the velocity at this waypoint. A value of 1 means the robot will move at the maximum speed, while values less than 1 will slow down the motion.
    """
    acceleration_factor: float = 1
    """
    A scaling factor for the acceleration at this waypoint. A value of 1 means the robot will move at the maximum speed, while values less than 1 will slow down the motion.
    """


class RobotConfig(BaseModel):
    name: str | None = Field(None, examples=["alpha"])
    """
    Robot name from URDF
    """
    number_joints: int | None = Field(None, examples=[6])
    """
    Number of actuated joints
    """
    joints: list[JointConfig] | None = None


class MoveWaypoints(BaseModel):
    command_id: UUID
    """
    Unique identifier for the command.
    """
    waypoints: list[Waypoint]
    """
    List of waypoints for the movement.
    """
    add_start: bool | None = None
    """
    if true, current joint state is added as trajectory start
    """


class ProgramsExecutorStatus(BaseModel):
    execution: ProgramExecution | None = None
    status: ExecutorStatus
    sigkill: bool = False
    """
    Whether to use SIGKILL to stop the program execution. If false, SIGTERM will be used.
    """


class IOStates(BaseModel):
    digital_inputs: list[DigitalIO] | None = None
    digital_outputs: list[DigitalIO] | None = None
    analog_inputs: list[AnalogIO] | None = None
    analog_outputs: list[AnalogIO] | None = None


class Token(TokenInfo):
    token: str


class TrajectoryGeneration(BaseModel):
    waypoints: list[Waypoint] = Field(..., min_length=1)
    """
    List of waypoints to generate trajectory for
    """
    motion_type: MotionType
    """
    Type of motion planning to use
    """
    add_start: bool | None = None
    """
    if true, current joint state is added as trajectory start
    """


class GeneratedTrajectory(BaseModel):
    waypoints: Trajectory
