# generated by datamodel-codegen:
#   filename:  openapi.yml
#   timestamp: 2026-02-10T10:24:25+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum, IntEnum
from ipaddress import IPv4Address
from uuid import UUID

from pydantic import BaseModel, EmailStr, Field, RootModel, SecretStr


class DeviceID(BaseModel):
    device_id: str = Field(..., examples=['f15bb7fca5f6408a8d9e0bca05bd5cf0'])


class Joints(RootModel[list[float]]):
    root: list[float] = Field(
        ...,
        description='The number of joints should be equal to the number of joints of the robot',
        examples=[[0.0, 1.25, 0.0, 0.0, 0.0, 0.0]],
    )


class Point(BaseModel):
    x: float
    y: float
    z: float


class Quaternion(BaseModel):
    x: float
    y: float
    z: float
    w: float


class Planner(Enum):
    RRTConnect = 'RRTConnect'
    RRT_ = 'RRT*'
    PRM_ = 'PRM*'
    LIN = 'LIN'
    PTP = 'PTP'
    CIRC = 'CIRC'


class PIDGains(BaseModel):
    p: float | None = Field(None, description='Proportional gain')
    i: float | None = Field(None, description='Integral gain')
    d: float | None = Field(None, description='Derivative gain')
    ff: float | None = Field(None, description='Feed-forward gain')
    max_i: float | None = Field(None, description='Maximum integral term')
    max_out: float | None = Field(None, description='Maximum output')


class Mode(IntEnum):
    integer_1 = 1
    integer_2 = 2
    integer_3 = 3


class ModeName(Enum):
    trajectory = 'trajectory'
    jog = 'jog'
    speed = 'speed'


class ControlMode(BaseModel):
    mode: Mode = Field(
        ...,
        description='Control mode identifier:\n- 1: TRAJECTORY (default) - Command controlled by trajectory executor, position regulation active\n- 2: JOG - Command generated by jog interface, position regulation active\n- 3: SPEED - Manual speed command, position regulation inactive\n',
        examples=[1],
    )
    mode_name: ModeName = Field(
        ..., description='Human-readable control mode name', examples=['trajectory']
    )


class MoveJoints(BaseModel):
    command_id: UUID = Field(..., description='Unique identifier for the command.')
    joints: Joints
    planner: Planner | None = Field(
        None,
        description='The motion planner to use for generating the joint movement trajectory. If not specified, the default planner will be used.\n',
    )


class FeedbackResponse(BaseModel):
    feedback_id: UUID = Field(
        ...,
        description='Unique identifier for the feedback of the corresponding action.',
    )


class Type(Enum):
    python3_9 = 'python3.9'
    python3_10 = 'python3.10'
    python3_11 = 'python3.11'
    python3_12 = 'python3.12'
    golang = 'golang'


class Program(BaseModel):
    id: UUID | None = None
    name: str | None = Field(None, description='The name of the program.')
    type: Type | None = None


class Type1(Enum):
    python = 'python'


class UploadProgram(BaseModel):
    file: bytes
    name: str | None = Field(
        None,
        description='The name of the program. If not provided, the file name will be used.',
    )
    type: Type1


class ProgramExecutionContext(BaseModel):
    environment: dict[str, str] | None = None
    arguments: list[str] | None = None


class ExecutorStatus(Enum):
    running = 'running'
    completed = 'completed'
    failed = 'failed'
    paused = 'paused'
    stopped = 'stopped'


class TrajectoryExecutorStatus(BaseModel):
    command_id: UUID | None = Field(
        None, description='Unique identifier for the move command.'
    )
    status: ExecutorStatus


class Value(Enum):
    HIGH = 'HIGH'
    LOW = 'LOW'


class DigitalIO(BaseModel):
    id: UUID | None = Field(
        None, description='The unique identifier of the digital input/output.'
    )
    value: Value | None = Field(
        None, description='The value of the digital input/output.'
    )


class AnalogIO(BaseModel):
    id: UUID | None = Field(
        None, description='The identifier of the analog input/output.'
    )
    value: float | None = Field(
        None, description='The value of the analog input/output, in volts.'
    )


class Login(BaseModel):
    login: str
    password: str
    expires_at: datetime | None = None


class Role(BaseModel):
    id: int
    name: str


class NewUser(BaseModel):
    email: EmailStr
    name: str
    role_id: int
    password: str


class TokenCreation(BaseModel):
    expires_at: datetime


class UpdatePassword(BaseModel):
    old_password: str
    new_password: str


class MotionType(Enum):
    p2p_articular = 'p2p_articular'
    p2p_linear = 'p2p_linear'
    waypoints = 'waypoints'


class JointsStamped(BaseModel):
    joints: Joints
    timestamp: float = Field(
        ..., description='Timestamp in seconds from trajectory start'
    )
    velocities: list[float] | None = Field(
        None, description='Joint velocities at this timestamp (optional)'
    )
    accelerations: list[float] | None = Field(
        None, description='Joint accelerations at this timestamp (optional)'
    )


class TrajectoryExecution(BaseModel):
    command_id: UUID = Field(..., description='Unique identifier for the command.')
    trajectory: list[JointsStamped] = Field(
        ..., description='Pre-computed trajectory to execute', min_length=1
    )


class NetworkInterfaceType(Enum):
    ethernet = 'ethernet'
    wifi = 'wifi'


class NetworkIpConfig(BaseModel):
    ip: IPv4Address = Field(
        ..., description='Static IP address assigned to the device.'
    )
    netmask: IPv4Address = Field(..., description='Subnet mask for the network.')
    gateway: IPv4Address = Field(..., description='Default gateway IP address.')
    dns: list[IPv4Address] | None = Field(
        None, description='List of DNS server IP addresses.'
    )
    dhcp: bool = Field(
        ...,
        description='Indicates whether DHCP is enabled for the network configuration. If true, the IP, netmask, gateway, and DNS fields may be ignored.',
    )


class NetworkInterfaceConfigEthernet(BaseModel):
    link_local: bool = Field(
        ...,
        description='Indicates whether link-local addressing (169.254.x.x) is enabled in fallback for the Ethernet interface.',
    )


class NetworkInterfaceConfigWiFi(BaseModel):
    ssid: str
    username: str | None = None
    password: SecretStr | None = None


class NetworkInterfaceConfig(BaseModel):
    enabled: bool = Field(
        ..., description='Indicates whether the network interface is enabled.'
    )
    ipv4: NetworkIpConfig
    ethernet: NetworkInterfaceConfigEthernet | None = None
    wifi: NetworkInterfaceConfigWiFi | None = None


class Pose(BaseModel):
    position: Point
    orientation: Quaternion


class JointConfig(BaseModel):
    name: str | None = Field(None, description='Joint name', examples=['joint_1'])
    type: str | None = Field(
        None,
        description='Joint type (revolute, prismatic, continuous)',
        examples=['revolute'],
    )
    position_limit_min: float | None = Field(
        None,
        description='Minimum position limit (radians or meters)',
        examples=[-3.14159],
    )
    position_limit_max: float | None = Field(
        None,
        description='Maximum position limit (radians or meters)',
        examples=[3.14159],
    )
    velocity_limit: float | None = Field(
        None, description='Maximum velocity limit (rad/s or m/s)', examples=[2.0]
    )
    acceleration_limit: float | None = Field(
        None, description='Maximum acceleration limit (rad/s² or m/s²)', examples=[5.0]
    )
    effort_limit: float | None = Field(
        None, description='Maximum effort/torque limit (Nm or N)', examples=[10.0]
    )
    pid_position: PIDGains | None = None
    pid_velocity: PIDGains | None = None


class MoveFrame(BaseModel):
    command_id: UUID = Field(..., description='Unique identifier for the command.')
    pose: Pose
    reference_frame: str | None = Field(
        None,
        description="The reference frame for the movement. If not specified, defaults to the robot's base frame.",
    )
    planner: Planner | None = None


class ExecuteProgram(BaseModel):
    execution_id: UUID
    context: ProgramExecutionContext


class ProgramExecution(BaseModel):
    id: UUID
    programId: UUID
    context: ProgramExecutionContext
    startedAt: datetime
    finishedAt: datetime
    exitCode: int
    status: ExecutorStatus | None = None


class User(BaseModel):
    id: UUID
    login: str
    name: str
    role: Role


class TokenInfo(TokenCreation):
    id: UUID
    expires_at: datetime
    created_at: datetime


class Trajectory(BaseModel):
    waypoints: list[JointsStamped] = Field(
        ..., description='Generated trajectory as array of timestamped joint positions'
    )


class NetworkInterfaceStatus(BaseModel):
    id: str = Field(..., description='Unique identifier for the network interface.')
    type: NetworkInterfaceType
    mac_address: str = Field(..., description='MAC address of the network interface.')
    connected: bool = Field(
        ...,
        description='Indicates whether the network interface is currently connected.',
    )
    state: NetworkIpConfig
    ethernet: NetworkInterfaceConfigEthernet | None = None
    wifi: NetworkInterfaceConfigWiFi | None = None


class Waypoint(BaseModel):
    joints: Joints | None = None
    pose: Pose | None = None
    frame_id: str | None = Field(
        None, description='Identifier for the frame associated with the waypoint.'
    )
    reference_frame: str | None = Field(
        None,
        description="The reference frame for the movement. If not specified, defaults to the robot's base frame.",
    )
    planner: Planner | None = None
    blending_radius: float | None = Field(
        0,
        description='The blending radius in meters for smooth pass-through motion at this waypoint. A value of 0 means the robot will stop at this waypoint. Non-zero values enable continuous motion through intermediate waypoints.',
    )
    velocity_factor: float | None = Field(
        1,
        description='A scaling factor for the velocity at this waypoint. A value of 1 means the robot will move at the maximum speed, while values less than 1 will slow down the motion.',
    )
    acceleration_factor: float | None = Field(
        1,
        description='A scaling factor for the acceleration at this waypoint. A value of 1 means the robot will move at the maximum speed, while values less than 1 will slow down the motion.',
    )


class RobotConfig(BaseModel):
    name: str | None = Field(
        None, description='Robot name from URDF', examples=['alpha']
    )
    number_joints: int | None = Field(
        None, description='Number of actuated joints', examples=[6]
    )
    joints: list[JointConfig] | None = None


class MoveWaypoints(BaseModel):
    command_id: UUID = Field(..., description='Unique identifier for the command.')
    waypoints: list[Waypoint] = Field(
        ..., description='List of waypoints for the movement.'
    )


class ProgramsExecutorStatus(BaseModel):
    execution: ProgramExecution | None = None
    status: ExecutorStatus


class Token(TokenInfo):
    token: str


class TrajectoryGeneration(BaseModel):
    waypoints: list[Waypoint] = Field(
        ..., description='List of waypoints to generate trajectory for', min_length=1
    )
    motion_type: MotionType = Field(..., description='Type of motion planning to use')
    add_start: bool | None = Field(
        None, description='if true, current joint state is added as trajectory start'
    )
