# generated by datamodel-codegen:
#   filename:  openapi.yml
#   timestamp: 2025-07-18T09:35:54+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List
from uuid import UUID

from pydantic import BaseModel, EmailStr, Field, RootModel


class Joints(RootModel[List[float]]):
    root: List[float] = Field(
        ...,
        description='The number of joints should be equal to the number of joints of the robot',
        examples=[[0.0, 1.25, 0.0, 0.0, 0.0, 0.0]],
    )


class MoveJoints(BaseModel):
    command_id: UUID = Field(..., description='Unique identifier for the command.')
    joints: Joints


class MoveResponse(BaseModel):
    command_id: UUID = Field(..., description='Unique identifier for the move command.')


class Point(BaseModel):
    x: float | None = None
    y: float | None = None
    z: float | None = None


class Quaternion(BaseModel):
    x: float | None = None
    y: float | None = None
    z: float | None = None
    w: float | None = None


class Pose(BaseModel):
    position: Point | None = None
    orientation: Quaternion | None = None


class Type(Enum):
    python = 'python'
    blockly = 'blockly'


class Program(BaseModel):
    id: str | None = None
    type: Type | None = None
    file: bytes | None = None


class Status(Enum):
    running = 'running'
    paused = 'paused'
    stopped = 'stopped'
    completed = 'completed'
    failed = 'failed'


class ProgramExecution(BaseModel):
    id: str | None = None
    status: Status | None = None
    start_time: datetime | None = None
    end_time: datetime | None = None


class Value(Enum):
    HIGH = 'HIGH'
    LOW = 'LOW'


class DigitalIO(BaseModel):
    id: str | None = Field(None, description='The unique identifier of the digital input/output.')
    value: Value | None = Field(None, description='The value of the digital input/output.')


class AnalogIO(BaseModel):
    id: str | None = Field(None, description='The identifier of the analog input/output.')
    value: float | None = Field(None, description='The value of the analog input/output, in volts.')


class Login(BaseModel):
    email: EmailStr
    password: str
    expires_at: datetime | None = None


class Role(BaseModel):
    id: int
    name: str


class NewUser(BaseModel):
    email: EmailStr
    name: str
    role_id: int
    password: str


class TokenCreation(BaseModel):
    expires_at: datetime


class UpdatePassword(BaseModel):
    old_password: str
    new_password: str


class User(BaseModel):
    id: UUID
    email: EmailStr
    name: str
    role: Role


class TokenInfo(TokenCreation):
    id: UUID
    expires_at: datetime
    created_at: datetime


class Token(TokenInfo):
    token: str
